### ISSUE TITLE
Fix on_conflict handling

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#102]
We currently have two excluded tags:
```
:with_conflict_target,
:without_conflict_target,
```

Due to the underlying tests failing. SQLite does support pretty robust on-conflict handling, so we should be able to make these tests pass. See `upsert-clause` at https://sqlite.org/lang_insert.html

**Comment by warmwaffles** [comment]
I actually am having some issues with handling the on conflict stuff.

```elixir
  def upsert_company(external_id, name) do
    %Company{}
    |> Company.changeset(%{external_id: external_id, name: name})
    |> Repo.insert(on_conflict: {:replace, [:name]})
  end
```

```
** (MatchError) no match of right hand side value: [:name]
    (exqlite 0.4.8) lib/ecto/adapters/exqlite/connection.ex:188: Ecto.Adapters.Exqlite.Connection.update_all/2
    (exqlite 0.4.8) lib/ecto/adapters/exqlite/connection.ex:668: Ecto.Adapters.Exqlite.Connection.on_conflict/2
    (exqlite 0.4.8) lib/ecto/adapters/exqlite/connection.ex:263: Ecto.Adapters.Exqlite.Connection.insert/7
    (exqlite 0.4.8) lib/ecto/adapters/exqlite.ex:2: Ecto.Adapters.Exqlite.insert/6
    (ecto 3.5.8) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
    (ecto 3.5.8) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
```

I'll start diving into this today.
