### ISSUE TITLE
Error :arguments_wrong_length on preload

### ISSUE THREAD

**Issue by lawik** [warmwaffles/exqlite#64]
Hey

Nice to see an Ecto 3 SQLite library. I'm thrilled about this! :)

I just tried to use it with an existing project and after some modifications (remove ALTER TABLE migrations, remove :map type field) it seemed to work.

Until I hit this error.

Git repo with branch: https://github.com/lawik/noted/tree/exqlite

Trying to run this code:

```
  def list_notes(user_id) do
    query =
      from n in Note,
        where: [user_id: ^user_id],
        preload: [:tags, :files]

    Repo.all(query)
  end
```

```
iex(2)> Noted.Notes.list_notes(1)
[debug] QUERY OK source="notes" db=0.0ms queue=0.1ms idle=1857.2ms
SELECT n0.id, n0.body, n0.title, n0.user_id, n0.inserted_at, n0.updated_at FROM notes AS n0 WHERE (n0.user_id = ?) [1]
[debug] QUERY ERROR source="files" db=11.7ms queue=0.2ms idle=28.1ms
SELECT f0.id, f0.mimetype, f0.path, f0.size, f0.note_id, f0.inserted_at, f0.updated_at, f0.note_id FROM files AS f0 WHERE (f0.note_id IN (?,?)) ORDER BY f0.note_id [[2, 1]]
[error] GenServer #PID<0.411.0> terminating
** (DBConnection.ConnectionError) client #PID<0.487.0> stopped: ** (WithClauseError) no with clause matching: {:error, %Exqlite.Error{message: :arguments_wrong_length}, %Exqlite.Connection{db: #Reference<0.1830523906.2284716050.207239>, path: "database.db", status: :busy, transaction_status: :idle}}
    (exqlite 0.4.1) lib/exqlite/connection.ex:443: Exqlite.Connection.execute/4
    (db_connection 2.3.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.3.1) lib/db_connection.ex:1272: DBConnection.run_execute/5
    (db_connection 2.3.1) lib/db_connection.ex:1359: DBConnection.run/6
    (db_connection 2.3.1) lib/db_connection.ex:557: DBConnection.parsed_prepare_execute/5
    (db_connection 2.3.1) lib/db_connection.ex:550: DBConnection.prepare_execute/4
    (exqlite 0.4.1) lib/ecto/adapters/exqlite/connection.ex:46: Ecto.Adapters.Exqlite.Connection.prepare_execute/5
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:692: Ecto.Adapters.SQL.execute!/4
    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto 3.5.8) lib/ecto/repo/preloader.ex:229: Ecto.Repo.Preloader.fetch_query/8
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

    (db_connection 2.3.1) lib/db_connection/connection.ex:183: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:236: :proc_lib.wake_up/3 
Last message: {:"$gen_cast", {:stop, #Reference<0.1830523906.2284716033.212081>, %DBConnection.ConnectionError{message: "client #PID<0.487.0> stopped: ** (WithClauseError) no with clause matching: {:error, %Exqlite.Error{message: :arguments_wrong_length}, %Exqlite.Connection{db: #Reference<0.1830523906.2284716050.207239>, path: \"database.db\", status: :busy, transaction_status: :idle}}\n    (exqlite 0.4.1) lib/exqlite/connection.ex:443: Exqlite.Connection.execute/4\n    (db_connection 2.3.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4\n    (db_connection 2.3.1) lib/db_connection.ex:1272: DBConnection.run_execute/5\n    (db_connection 2.3.1) lib/db_connection.ex:1359: DBConnection.run/6\n    (db_connection 2.3.1) lib/db_connection.ex:557: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.3.1) lib/db_connection.ex:550: DBConnection.prepare_execute/4\n    (exqlite 0.4.1) lib/ecto/adapters/exqlite/connection.ex:46: Ecto.Adapters.Exqlite.Connection.prepare_execute/5\n    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:692: Ecto.Adapters.SQL.execute!/4\n    (ecto_sql 3.5.4) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5\n    (ecto 3.5.8) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4\n    (ecto 3.5.8) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3\n    (ecto 3.5.8) lib/ecto/repo/preloader.ex:229: Ecto.Repo.Preloader.fetch_query/8\n    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n", reason: :error, severity: :error}, %Exqlite.Connection{db: #Reference<0.1830523906.2284716050.207239>, path: "database.db", status: :busy, transaction_status: :idle}}}
State: {Exqlite.Connection, %Exqlite.Connection{db: #Reference<0.1830523906.2284716050.207239>, path: "database.db", status: :busy, transaction_status: :idle}}
```

I don't have an opportunity to sit down and figure if this is all WHERE x IN y or whether it has to do with Ecto preloads or if my schemas are screwy. It worked fine on Postgres and explodes on this.

If you want to reproduce with my code, set up the app, get a Telegram bot API key (not too complicated if you have Telegram, just talk to the BotFather bot) put that and the bot name in environment variables as noted in the README and use the bot to authenticate and then send a photo. This breaks the list_notes function call with the above error.

**Comment by warmwaffles** [comment]
It should also be noted https://sqlite.org/np1queryprob.html#n_1_queries_are_not_a_problem_with_sqlite

But this is still something I'll look into.

**Comment by lawik** [comment]
Interesting, hadn't thought of that. But yeah, the error remains :)

**Comment by warmwaffles** [comment]
I'm able to recreate this. Working on a fix now.

**Comment by kevinlang** [comment]
There is also a set of `preload.exs` integration tests we can onboard in `integration_test/`, for testing out the fix.

**Comment by warmwaffles** [comment]
@kevinlang that is exactly what I was doing. Although I'm surprised there isn't a test within the connection_exs that doesn't check for a preload join. I'm gonna add one there as well.

**Comment by warmwaffles** [comment]
@lawik a work around right now would be to do 

```elixir
  def list_notes(user_id) do
    query =
      from n in Note,
        select: n,
        where: [user_id: ^user_id],
        preload: [:tags, :files]

    Repo.all(query)
  end
```

Notice the `select:`. I think this may be an issue with ecto itself. I need to do some more testing with ecto to figure out where the issue resides.
